"""Stage 1 — script.

Mode A: user supplies a script; we keep it verbatim.
Mode B: LLM writes one from an idea, sized to the target duration.
Mode C: the human edits either result (the UI PUTs `script` back).

Word budget: ~2.6 words/second of finished narration is a reliable rate for
measured, explainer-style delivery. We tell the model that explicitly because
"60 seconds" alone produces scripts that run 2x long.
"""
from __future__ import annotations

from ..manifest import Project
from ..providers import llm

WORDS_PER_SECOND = 2.6

SYSTEM = """You are a short-form video scriptwriter. You write narration that is
spoken aloud — no headings, no stage directions, no speaker labels, no emoji,
no markdown. Plain sentences only.

Rules:
- Open with a hook in the first sentence. No throat-clearing.
- Concrete and specific. Prefer a real image over an abstraction.
- One idea per sentence; sentences short enough to say in one breath.
- End on a line that lands, not a summary of what you just said.
- Never mention that you are an AI or that this is a script."""


def generate(project_id: str, *, script: str = "", extra_direction: str = "") -> Project:
    proj = Project.load(project_id)

    if script.strip():
        proj.script = script.strip()
        proj.note("script supplied by human (mode A)")
        proj.save()
        return proj

    budget = int(proj.target_duration * WORDS_PER_SECOND)
    user = (
        f"Idea: {proj.idea}\n"
        f"Target length: {proj.target_duration} seconds of narration, which is "
        f"about {budget} words. Stay within {budget - 12}-{budget + 12} words.\n"
        f"{extra_direction}\n\n"
        "Return JSON only, with keys:\n"
        '  "title": short punchy title (max 8 words)\n'
        '  "premise": one sentence describing the argument\n'
        '  "script": the full narration as plain prose\n'
    )
    data = llm.chat_json(SYSTEM, user, temperature=0.8, max_tokens=6000)
    proj.title = (data.get("title") or proj.title).strip()
    proj.premise = (data.get("premise") or "").strip()
    proj.script = (data.get("script") or "").strip()
    if not proj.script:
        raise SystemExit("model returned an empty script")
    wc = len(proj.script.split())
    proj.note(f"script generated by LLM ({wc} words, ~{wc / WORDS_PER_SECOND:.0f}s)")
    proj.save()
    print(f"[script] {proj.title!r} — {wc} words (~{wc / WORDS_PER_SECOND:.0f}s)")
    return proj


def set_script(project_id: str, script: str) -> Project:
    """Mode C — human edit. Invalidates downstream scene narration deliberately."""
    proj = Project.load(project_id)
    proj.script = script.strip()
    proj.note("script edited by human")
    proj.save()
    return proj
